"""add user_id to chatmessage and fix chat_id type

Revision ID: 008fb82261bc
Revises: bf58a291441b
Create Date: 2026-04-10 22:36:15.213864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008fb82261bc'
down_revision = 'bf58a291441b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
