"""Aggiunta tabella diario

Revision ID: e46283e2cec3
Revises: bf58a291441b
Create Date: 2026-04-12 22:49:53.900225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e46283e2cec3'
down_revision = 'bf58a291441b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('memory_text', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entry_user_id'), 'diary_entry', ['user_id'], unique=False)
    op.add_column('chat_message', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.add_column('chat_message', sa.Column('username', sa.String(length=255), nullable=True))

    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_column('chat_message', 'username')
    op.drop_column('chat_message', 'user_id')
    op.drop_index(op.f('ix_diary_entry_user_id'), table_name='diary_entry')
    op.drop_table('diary_entry')
    # ### end Alembic commands ###
